source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "puma", ">= 5.0"
gem "sprockets-rails", :require => 'sprockets/railtie'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
